//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spammer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.SendEmails = new HashSet<SendEmail>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string AuthCode { get; set; }
        public string SessionKey { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<SendEmail> SendEmails { get; set; }
    }
}
